platform:
  - x64

cache:
  - '%LOCALAPPDATA%\electron\Cache'
  - node_modules -> package.json

install:
  - systeminfo | findstr /C:"OS"
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - ps: Install-Product node 10.13.0 x64
  - yarn install --frozen-lockfile

build_script:
  - node build\grunt.js
  - yarn generate
  - yarn lint-windows
  - yarn test-node

test_script:
  - node build\grunt.js test

environment:
  SIGNAL_ENV: production
